// Auto-generated by scripts/embed-pubkey.ts at publish time.
// Old keys are NEVER removed — needed to validate unexpired JWTs signed by prior keys.
// The 'kid' claim in the JWT header selects the correct key.
export const BUNDLED_PUBLIC_KEYS: Record<string, string> = {
  // 'k1': '-----BEGIN PUBLIC KEY-----\n...',
};
